### ISSUE TITLE
document which regexp type is used

### ISSUE THREAD

**Issue by calestyo** [bdrung/restricted-ssh-commands#1]
Hi.

It would be nice if the manpage could tell which exact type of regular expressions are supported (e.g. PCRE, POSIX BRE, POSIX ERE, etc.)

Cheers,
Chris.

**Comment by bdrung** [comment]
The man page says `extended regular expression` in section FILES. I'll change that to `POSIX extended regular expression (ERE)`. Will that enough to clarify it? If not, patches are welcome. ;)

**Comment by calestyo** [comment]
+1 :-)
