### ISSUE TITLE
Did I find a bug?

### ISSUE THREAD

**Issue by Skeeve** [bdrung/restricted-ssh-commands#5]
config has

```
^ls( [^;]*)*$
```

Now I simply send

```
ssh user@host "ls -al inbox
touch inbox/x
ls -al inbox"
```

This will happily create the x-file.

**Comment by bdrung** [comment]
No, this is how it works. Your negative bracket expression `[^;]` also matches newlines. This is already documented in the [restricted-ssh-commands man page](https://github.com/bdrung/restricted-ssh-commands/blob/master/restricted-ssh-commands.pod) under [SECURITY NOTES](https://github.com/bdrung/restricted-ssh-commands/blob/master/restricted-ssh-commands.pod#security-notes).

**Comment by Skeeve** [comment]
Fair enough.

Thanks for pointing me to the man page… Ever so often I forget to check them. Sorry.

Too bad `\n` isn't possible to be used. Or that rsc doesn't split the commands. But I guess splitting would result in other issues.

**Comment by bdrung** [comment]
I thought about other solutions, but positive bracket expressions worked for me well enough and they are safe (= easy to check if they can be abused).

**Comment by Skeeve** [comment]
It's not as flexible as I thought, but for my use case I think it's also sufficient. I also had `\n` in my negative class but it didn't work. Coming from perl (using it since 1995) I didn't realise `\n` could be unknown to any regexp parser ;) 

Regexes are not very well suited to parse balanced quotes so it's too complicated to do proper command-splitting.

At the moment I'm satisfied with what's possible.
